console.log("EXERCITIUL 3");
let luni = 1;
let marti = 2;
let miercuri = 3;
let joi = 4;
let vineri = 5;
let sambata = 6;
let duminica = 7;
console.log(`Luni: ${luni}`);
console.log(`Marti: ${marti}`);
console.log(`Miercuri: ${miercuri}`);
console.log(`Joi: ${joi}`);
console.log(`vineri: ${vineri}`);
console.log(`Sambata: ${sambata}`);
console.log(`Duminica: ${duminica}`);