console.log("EXERCITIUL 1");
let a;
console.log("a a fost declarat");
console.log("valoarea lui a este " + a);
a = 10;
console.log("Lui a i s-a atribuit valoarea 10");
console.log("valoarea lui a este " + a);
a = a + 10;
console.log("a si-a schimbat valoarea");
console.log("Valoarea lui a este " + a);
a = a + 1;
console.log("a si-a marit valoarea cu 1");
console.log("valoarea lui a este " + a);
