console.log("EXERCITIUL 3");
let luni = 0;
console.log("Luni: " + luni);
let marti = 1;
console.log("Marti: " + marti);
let miercuri = 2;
console.log("Miercuri: " + miercuri);
let joi = 3;
console.log("Joi: " + joi);
let vineri = 4;
console.log("Vineri: " + vineri);
let sambata = 5;
console.log("Sambata: " + sambata);
let duminica = 6;
console.log("duminica: " + duminica);
