console.log("EXERCITIUL 2");
let b;
console.log("b a fost declarat");
console.log("valoarea lui b este " + b);
b = 10;
console.log("Lui b i s-a atribuit valoarea 10");
console.log("valoarea lui b este " + b);
b = b + 10;
console.log("b si-a schimbat valoarea");
console.log("Valoarea lui b este " + b);
b = b - 5;
console.log("b si-a micsorat valoarea cu 5");
console.log("valoarea lui b este " + b);
